-- Citizen.txt Description
CREATE TABLE CITIZEN (
	C_ID INT,
	C_NAME VARCHAR(10),
	C_HOME VARCHAR(10),
	AGE INT,
	OCCUPATION VARCHAR(15),
	GENDER VARCHAR(6),
	SALARY INT,
	CONSTRAINT PK_CITIZEN PRIMARY KEY (C_ID)
);

INSERT INTO CITIZEN VALUES (1, 'Alice', 'Dhaka', 25, 'Teacher', 'Male', 50000);
INSERT INTO CITIZEN VALUES (2, 'Bob', 'Dhaka', 56, 'Service', 'Male', 60000);
INSERT INTO CITIZEN VALUES (3, 'Charlie', 'Ctg', 71, 'Retired', 'Male', 10000);
INSERT INTO CITIZEN VALUES (4, 'Erin', 'Ctg', 13, 'Student', 'Female', 500);
INSERT INTO CITIZEN VALUES (5, 'Dave', 'Dhaka', 45, 'Service', 'Male', 40000);
INSERT INTO CITIZEN VALUES (6, 'Faythe', 'Gazipur', 54, 'Doctor', 'Female', 55000);
INSERT INTO CITIZEN VALUES (7, 'Grace', 'Gazipur', 65, 'Musician', 'Female', 5000);
INSERT INTO CITIZEN VALUES (8, 'Ivan', 'Dhaka', 56, 'Engineer', 'Male', 60000);
INSERT INTO CITIZEN VALUES (9, 'Frank', 'Ctg', 23, 'Student', 'Male', 1000);
INSERT INTO CITIZEN VALUES (10, 'Micheal', 'Comilla', 32, 'Teacher', 'Male', 45000);
INSERT INTO CITIZEN VALUES (11, 'Niaj', 'Comilla', 51, 'Farmer', 'Male', 20000);
INSERT INTO CITIZEN VALUES (12, 'Heidi', 'Khulna', 15, 'Student', 'Female', 1500);
INSERT INTO CITIZEN VALUES (13, 'Ted', 'Ctg', 25, 'Business', 'Male', 100000);
INSERT INTO CITIZEN VALUES (14, 'Walter', 'Comilla', 52, 'Doctor', 'Male', 70000);
INSERT INTO CITIZEN VALUES (15, 'Victor', 'Gazipur', 53, 'Teacher', 'Male', 50000);
INSERT INTO CITIZEN VALUES (16, 'Judy', 'Dhaka', 35, 'Musician', 'Female', 50000);
INSERT INTO CITIZEN VALUES (17, 'Pat', 'Khulna', 43, 'Service', 'Male', 50000);
INSERT INTO CITIZEN VALUES (18, 'Olivia', 'Khulna', 34, 'Service', 'Female', 45000);
INSERT INTO CITIZEN VALUES (19, 'Trent', 'Ctg', 16, 'Student', 'Male', 500);
INSERT INTO CITIZEN VALUES (20, 'Peggy', 'Comilla', 32, 'Business', 'Female', 120000);
INSERT INTO CITIZEN VALUES (21, 'Wendy', 'Ctg', 25, 'Musician', 'Female', 100000);
INSERT INTO CITIZEN VALUES (22, 'Oscar', 'Gazipur', 14, 'Student', 'Male', 400);
INSERT INTO CITIZEN VALUES (23, 'Mallet', 'Dhaka', 25, 'Engineer', 'Male', 50000);

SELECT MAX(SALARY) FROM CITIZEN;

SELECT C_NAME, SALARY, AGE
FROM CITIZEN
WHERE C_NAME NOT LIKE '%EE%';

SELECT C_NAME, OCCUPATION
FROM CITIZEN
WHERE C_NAME LIKE '%AA%'
OR C_NAME LIKE '%LL%';

SELECT C_NAME
FROM CITIZEN
WHERE C_NAME LIKE '__y%';

SELECT C_NAME
FROM CITIZEN
WHERE C_NAME LIKE 'A___%';

SELECT SUM(SALARY)
FROM CITIZEN
WHERE OCCUPATION = 'Teacher';

SELECT MAX(SALARY)
FROM CITIZEN
WHERE C_NAME LIKE 'A%';

SELECT DISTINCT SALARY
FROM CITIZEN
ORDER BY SALARY DESC
LIMIT 1 OFFSET 4;

SELECT COUNT(*)
FROM CITIZEN
WHERE OCCUPATION = 'Doctor';

SELECT COUNT(*)
FROM CITIZEN
WHERE GENDER = 'Male'
AND OCCUPATION = 'Musician';

SELECT C_NAME, SALARY
FROM CITIZEN
WHERE SALARY = (SELECT MAX(SALARY) FROM CITIZEN);

SELECT OCCUPATION, COUNT(*)
FROM CITIZEN
GROUP BY OCCUPATION;

SELECT OCCUPATION, MAX(SALARY)
FROM CITIZEN
GROUP BY OCCUPATION;

SELECT COUNT(DISTINCT C_HOME)
FROM CITIZEN
WHERE C_HOME LIKE '%aks%';

SELECT OCCUPATION, AVG(SALARY)
FROM CITIZEN
GROUP BY OCCUPATION
HAVING AVG(SALARY) >
(
	SELECT AVG(SALARY)
	FROM CITIZEN
);
